services:
  php:
    image: yiisoftware/yii2-php:8.4-fpm
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: testrootpass
      MARIADB_DATABASE: yii2basic
      MARIADB_USER: root
      MARIADB_PASSWORD:
  test_db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db_data_test:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: testrootpass
      MARIADB_DATABASE: yii2basic_test
      MARIADB_USER: root
      MARIADB_PASSWORD:
volumes:
  db_data:
  db_data_test:

