<?php

namespace app\modules\postal\sender\Type;

enum MiejscaPozostawieniaAwizoEnum: string {
    case SKRZYNKA_ODDAWCZA = 'SKRZYNKA_ODDAWCZA';
    case DRZWI_MIESZKANIA = 'DRZWI_MIESZKANIA';
    case DRZWI_INNEGO_POMIESZCZENIA = 'DRZWI_INNEGO_POMIESZCZENIA';
    case PRZY_WEJSCIU_NA_POSESJE = 'PRZY_WEJSCIU_NA_POSESJE';
    case SKRYTKA_POCZTOWA = 'SKRYTKA_POCZTOWA';
    case INNE_WIDOCZNE_MIEJSCE = 'INNE_WIDOCZNE_MIEJSCE';
    case DRZWI_BIURA = 'DRZWI_BIURA';
}
