<?php

namespace app\modules\postal\sender\Type;

enum PermisionType: string {
    case MANAGE_USERS = 'MANAGE_USERS';
    case TRANSMIT = 'TRANSMIT';
    case MANAGE_PROFILES = 'MANAGE_PROFILES';
    case MANAGE_ORGANIZATION_UNIT = 'MANAGE_ORGANIZATION_UNIT';
    case MANAGE_TEMPLATES = 'MANAGE_TEMPLATES';
    case EDIT_PARCELS = 'EDIT_PARCELS';
    case EDIT_PARCELS_FROM_TEMPLATES = 'EDIT_PARCELS_FROM_TEMPLATES';
    case MANAGE_ADDRESS_BOOK = 'MANAGE_ADDRESS_BOOK';
    case SAVE_SELF_SETTINGS = 'SAVE_SELF_SETTINGS';
    case MANAGE_DICTIONARIES = 'MANAGE_DICTIONARIES';
    case MANAGE_RETURN_DOCUMENTS_ADDRESSES = 'MANAGE_RETURN_DOCUMENTS_ADDRESSES';
    case VIEW_INVOICE = 'VIEW_INVOICE';
}
