<?php

namespace app\modules\postal\sender\Type;

enum PodmiotDoreczeniaEnum: string {
    case ADRESAT = 'ADRESAT';
    case PELNOLETNI_DOMOWNIK = 'PELNOLETNI_DOMOWNIK';
    case SASIAD = 'SASIAD';
    case DOZORCA_DOMU = 'DOZORCA_DOMU';
    case SOLTYS = 'SOLTYS';
    case ADMINISTRACJA_DOMU = 'ADMINISTRACJA_DOMU';
    case UPOWAZNIONY_PRACOWNIK = 'UPOWAZNIONY_PRACOWNIK';
    case PELNOMOCNIK_POCZTOWY = 'PELNOMOCNIK_POCZTOWY';
    case PRZEDSTAWICIEL_USTAWOWY = 'PRZEDSTAWICIEL_USTAWOWY';
    case PELNOMOCNIK_ADRESATA = 'PELNOMOCNIK_ADRESATA';
    case OSOBA_UPRAWNIONA_DO_REPREZENTACJI = 'OSOBA_UPRAWNIONA_DO_REPREZENTACJI';
    case SKRZYNKA_ODDAWCZA = 'SKRZYNKA_ODDAWCZA';
    case ADRESAT_KTORY_NIE_MOGL = 'ADRESAT_KTORY_NIE_MOGL';
    case OSOBA_UPRAWNIONA_DO_ODBIORU = 'OSOBA_UPRAWNIONA_DO_ODBIORU';
    case DOROSLY_DOMOWNIK = 'DOROSLY_DOMOWNIK';
    case OSOBA_UPOWAZNIONA_DO_ODB_KORESP = 'OSOBA_UPOWAZNIONA_DO_ODB_KORESP';
    case KIEROWNIK_JEDNOSTKI_LUB_UPOWAZNIONY = 'KIEROWNIK_JEDNOSTKI_LUB_UPOWAZNIONY';
    case PRZEDSTAWICIEL_ADRESATA = 'PRZEDSTAWICIEL_ADRESATA';
    case OSOBA_UPOWAZNIONA_DO_REPREZENT_ADRESATA = 'OSOBA_UPOWAZNIONA_DO_REPREZENT_ADRESATA';
    case OSOBA_UPOWAZNIONA_PRZEZ_PRACODAWCE = 'OSOBA_UPOWAZNIONA_PRZEZ_PRACODAWCE';
    case PRZELOZONY_ABW = 'PRZELOZONY_ABW';
    case PRZELOZONY_AW = 'PRZELOZONY_AW';
    case PRZELOZONY_CBA = 'PRZELOZONY_CBA';
    case PRZELOZONY_POLICJI = 'PRZELOZONY_POLICJI';
    case PRZELOZONY_SC = 'PRZELOZONY_SC';
    case PRZELOZONY_SG = 'PRZELOZONY_SG';
    case PRZELOZONY_SKW = 'PRZELOZONY_SKW';
    case PRZELOZONY_SW = 'PRZELOZONY_SW';
    case PRZELOZONY_SWW = 'PRZELOZONY_SWW';
    case PRZELOZONY_ZOLNIERZA = 'PRZELOZONY_ZOLNIERZA';
    case SKRYTKA_POCZTOWA = 'SKRYTKA_POCZTOWA';
    case PROKURENT = 'PROKURENT';
    case ZARZADCA_DOMU = 'ZARZADCA_DOMU';
    case OSOBA_UPOWAZNIONA_PRZEZ_KIER_WIEZIENIA = 'OSOBA_UPOWAZNIONA_PRZEZ_KIER_WIEZIENIA';
}
