<?php

namespace app\modules\postal\sender\Type;

enum PrintKindEnum: string {
    case ADDRESS_LABEL = 'ADDRESS_LABEL';
    case ADDRESS_LABEL_BY_GUID = 'ADDRESS_LABEL_BY_GUID';
    case CUSTOMS_DECLARATION = 'CUSTOMS_DECLARATION';
    case ADDRESS_LABEL_FOR_RETURN_DOCUMENTS = 'ADDRESS_LABEL_FOR_RETURN_DOCUMENTS';
    case CHECKLIST = 'CHECKLIST';
    case COLLECT_ON_DELIVERY_FORM = 'COLLECT_ON_DELIVERY_FORM';
    case WAYBILL = 'WAYBILL';
    case REPORT = 'REPORT';
    case ADDRESS_LABEL_FOR_ERETURN = 'ADDRESS_LABEL_FOR_ERETURN';
    case ADDRESS_LABEL_FOR_FOREGIN_RETURN = 'ADDRESS_LABEL_FOR_FOREGIN_RETURN';
}
