<?php

namespace app\modules\postal\sender\Type;

enum PrzyczynaZwrotuEnum: string {
    case ODMOWA = 'ODMOWA';
    case ADRESAT_ZMARL = 'ADRESAT_ZMARL';
    case ADRESAT_NIEZNANY = 'ADRESAT_NIEZNANY';
    case ADRESAT_WYPROWADZIL_SIE = 'ADRESAT_WYPROWADZIL_SIE';
    case ADRESAT_NIE_PODJAL = 'ADRESAT_NIE_PODJAL';
    case INNA = 'INNA';
    case ADRES_NIEPELNY = 'ADRES_NIEPELNY';
    case ADRES_BLEDNY = 'ADRES_BLEDNY';
    case ADRES_NIEZGODNY = 'ADRES_NIEZGODNY';
    case ADRES_NIEZNALEZIONY = 'ADRES_NIEZNALEZIONY';
    case ADRESAT_NIE_ZASTANO = 'ADRESAT_NIE_ZASTANO';
    case ADRESAT_NIE_ZGLASZA_SIE = 'ADRESAT_NIE_ZGLASZA_SIE';
    case ADRESAT_NIEOBECNY = 'ADRESAT_NIEOBECNY';
    case ADRESAT_NIEODNALEZIONY = 'ADRESAT_NIEODNALEZIONY';
    case ADRESAT_STRAJKUJE = 'ADRESAT_STRAJKUJE';
    case DO_NADAWCY_NA_POZNIEJ = 'DO_NADAWCY_NA_POZNIEJ';
    case MYLNE_SKIEROWANIE = 'MYLNE_SKIEROWANIE';
    case NADAWCA_ODMOWIL = 'NADAWCA_ODMOWIL';
    case NIE_PODJETO = 'NIE_PODJETO';
    case NIEZGODNE_WYMAGANIA = 'NIEZGODNE_WYMAGANIA';
    case ODMOWA_USZKODZENIA = 'ODMOWA_USZKODZENIA';
    case POBRANIE_NIEZGODNE = 'POBRANIE_NIEZGODNE';
    case USZKODZONA = 'USZKODZONA';
    case ZAMKNIETA_SIEDZIBA = 'ZAMKNIETA_SIEDZIBA';
}
