<?php

namespace app\modules\postal\sender\Type;

enum SerwisPrzesylkaProceduralnaType: string {
    case PROCEDURALNA_STANDARD_DWA_STOPNIE = 'PROCEDURALNA_STANDARD_DWA_STOPNIE';
    case PROCEDURALNA_VIP_DWA_STOPNIE = 'PROCEDURALNA_VIP_DWA_STOPNIE';
    case PROCEDURALNA_STANDARD_TRZY_STOPNIE = 'PROCEDURALNA_STANDARD_TRZY_STOPNIE';
    case PROCEDURALNA_VIP_TRZY_STOPNIE = 'PROCEDURALNA_VIP_TRZY_STOPNIE';
}
