<?php

namespace app\modules\postal\sender\Type;

enum TerminZwrotDokumentowBiznesowaType: string {
    case LIST_ZWYKLY_PRIORYTETOWY = 'LIST_ZWYKLY_PRIORYTETOWY';
    case LIST_ZWYKLY_EKONOMICZNY = 'LIST_ZWYKLY_EKONOMICZNY';
    case LIST_POLECONY_PRIORYTETOWY = 'LIST_POLECONY_PRIORYTETOWY';
    case LIST_POLECONY_EKONOMICZNY = 'LIST_POLECONY_EKONOMICZNY';
    case EKSPRES24 = 'EKSPRES24';
}
