<?php

namespace app\modules\postal\sender\Type;

enum ZwrotDokumentowPaczkowaType: string {
    case EKSPRES24 = 'EKSPRES24';
    case PACZKA_EKSTRA_24 = 'PACZKA_EKSTRA_24';
    case PACZKA_24 = 'PACZKA_24';
    case PACZKA_48 = 'PACZKA_48';
    case LIST_ZWYKLY_PRIORYTETOWY = 'LIST_ZWYKLY_PRIORYTETOWY';
    case LIST_ZWYKLY_EKONOMICZNY = 'LIST_ZWYKLY_EKONOMICZNY';
    case LIST_POLECONY_PRIORYTETOWY = 'LIST_POLECONY_PRIORYTETOWY';
    case LIST_POLECONY_EKONOMICZNY = 'LIST_POLECONY_EKONOMICZNY';
}
