<?php

use app\modules\postal\models\ShipmentDirectionInterface;

return [
    'sender' => [
        'id' => 1,
        'name' => 'Jan Kowalski',
        'postal_code' => '00123',
        'city' => 'Warszawa',
        'country' => 'PL',
        'option' => ShipmentDirectionInterface::DIRECTION_IN,
        'city_id' => 101,
        'street' => 'Marszałkowska',
        'apartment_number' => '5',
        'house_number' => '12A',
        'name_2' => 'Biuro',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'jan@example.com',
        'taxID' => '1234567890',
    ],
    'receiver' => [
        'id' => 2,
        'name' => 'Kowal Janowski',
        'postal_code' => '33210',
        'city' => 'Kraków',
        'country' => 'PL',
        'option' => ShipmentDirectionInterface::DIRECTION_OUT,
        'city_id' => 101,
        'street' => 'Piastowska',
        'apartment_number' => '1',
        'house_number' => '1',
        'name_2' => 'Kowal',
        'phone' => '123456789',
        'mobile' => '987654321',
        'contact_person' => '123456789',
        'email' => 'kowal@example.com',
        'taxID' => '1234567890',
    ],
    'address_only_required' => [
        'id' => 3,
        'name' => 'Firma ABC',
        'house_number' => '8',
        'postal_code' => '54321',
        'city' => 'Kraków',
        'country' => 'PL',
        'option' => ShipmentDirectionInterface::DIRECTION_OUT,
        'city_id' => null,
        'street' => null,
        'apartment_number' => null,
        'name_2' => null,
        'phone' => null,
        'mobile' => null,
        'contact_person' => null,
        'email' => null,
        'taxID' => null,
    ],
];
